language: cpp
compiler: clang
before_script:
- sudo apt install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list.d/xenial.list
- sudo apt update
- sudo apt install libspdlog-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package